### ISSUE TITLE
Add Telegram on the website

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2017#57]
I don't know what the organizers decided to use as communication chat for the conference but after 2016 edition we keep using [Telegram](https://telegram.org/). Any one interested to join the chat can do accessing https://telegram.me/scipyla. **Can we have a link to https://telegram.me/scipyla on the website**?

**Comment by xmnlab** [comment]
solo les pido que no usen este canal de telegram para las difusiones de
mensajes de operación del evento (ej: el almuerzo será en el local x, hubo
cambio de horarios, etc), pues creo muchos (lamentablemente) no estarán
presentes en el evento y eso sería algo ruidoso en el canal.

El 5 ene. 2017 15:56, "Raniere Silva" <notifications@github.com> escribió:

I don't know what the organizers decided to use as communication chat for
the conference but after 2016 edition we keep using Telegram
<https://telegram.org/>. Any one interested to join the chat can do
accessing https://telegram.me/scipyla. *Can we have a link to
https://telegram.me/scipyla <https://telegram.me/scipyla> on the website*?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/scipy-latinamerica/scipyla2017/issues/57>, or mute the
thread

**Comment by rgaiacs** [comment]
You normally set up an communication channel to be user only for those that are attending the conference. But the default channel of communication for the community should be listed on the website. Community members don't need to use/follow all but we should not discriminate any "official" channel.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by xmnlab** [comment]
i agree :)

El 7 ene. 2017 0:21, "Raniere Silva" <notifications@github.com> escribió:

You normally set up an communication channel to be user only for those that
are attending the conference. But the default channel of communication for
the community should be listed on the website. Community members don't need
to use/follow all but we should not discriminate any "official" channel.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/scipy-latinamerica/scipyla2017/issues/57#issuecomment-271056091>,
or mute the thread
